name: CD

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: docker login
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}   
        DOCKER_SECRET: ${{ secrets.DOCKER_SECRET }}  
      run: |
        docker login ghcr.io -u $DOCKER_USER -p $DOCKER_SECRET
    - name: Get commit id
      id: vars
      shell: bash
      run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
    - name: docker build
      run: docker build . -t ghcr.io/czm1k3/githubactionscd:${{ steps.vars.outputs.sha_short }} -t ghcr.io/czm1k3/githubactionscd:latest
    - name: docker push
      run: |
        docker push ghcr.io/czm1k3/githubactionscd:${{ steps.vars.outputs.sha_short }}
        docker push ghcr.io/czm1k3/githubactionscd:latest
        
