name: CD

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: docker login
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}   
        DOCKER_SECRET: ${{ secrets.DOCKER_SECRET }}  
      run: |
        docker login ghcr.io -u $DOCKER_USER -p $DOCKER_SECRET
    - name: docker build
      run: docker build . -t ghcr.io/czm1k3/githubactionscd:latest
    - name: docker push
      run: docker push ghcr.io/czm1k3/githubactionscd:latest
